apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-myapp
  namespace: tomcat-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-myapp
  template:
    metadata:
      labels:
        app: tomcat-myapp
    spec:
      containers:
      - name: tomcat
        image: climacs/tomcat
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-myapp-service
  namespace: tomcat-myapp
spec:
  selector:
    app: tomcat-myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
