apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-myapp
  namespace: helloworld-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-myapp
  template:
    metadata:
      labels:
        app: helloworld-myapp
    spec:
      containers:
      - name: hello-world
        image: hello-world
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-myapp-service
  namespace: helloworld-myapp
spec:
  selector:
    app: helloworld-myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
