apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cat-website-n
data:
  nginx.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        proxy_pass http://cat-website:8000;  # Change 'app' to 'cat-website'
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-website
  namespace: cat-website-n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat-website
  template:
    metadata:
      labels:
        app: cat-website
    spec:
      containers:
      - name: cat-website
        image: climacs/cat-website-app-intel-v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: cat-website
  namespace: cat-website-n
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: cat-website
