apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-myapp
  namespace: nginx-myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-myapp
  template:
    metadata:
      labels:
        app: nginx-myapp
    spec:
      containers:
      - name: nginx
        image: climacs/nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-myapp-service
  namespace: nginx-myapp
spec:
  selector:
    app: nginx-myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
